# Image
FROM node:12.4-alpine

# Set up work directory
WORKDIR /var/www/html

# global install & update
# RUN npm i -g npm && npm i -g yarn

# RUN rm yarn.lock
# RUN ls -lh
# RUN yarn
# RUN yarn build

# # start command
# CMD [ "yarn", "start" ]