name: staging_deploy
on:
  push:
    branches:
      - develop

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: SSH in staging server
        uses: garygrossgarten/github-action-ssh@release
        with:
          command: cd /var/www/html/staging/regenschori-web-staging && make staging-deploy --silent
          host: ${{ secrets.HOST }}
          port: ${{ secrets.PORT }}
          username: ${{ secrets.USERNAME }}
          privateKey: ${{ secrets.PRIVATE_KEY}}
